export default {
  // 公共数据字典，不允许添加除字典外的数据
  cdd: {
    mat_code: '物料编码',
    mat_name: '物料名称',
    mat_type: '物料类型',
    measure_unit: '计量单位',
    mat_spec: '物料规格',
    packing_spec: '包装规格',
    packing_unit: '包装单位',
    valid_period: '效期',
    valid_period_usage: '使用效期',
    validity_period: '有效期',
    reinspect_period: '复验期',
    batch_num: '批次号',
    inventory: '库存量',
    total_inventory: '库存总量',
    production_date: '生产日期',
    manufacturer: '生产商',
    manufacturer_batch: '生产商批次',
    quality_status: '质量状态',
    test_no: '化验单号',
    package_quantity: '包装数量',
    subbatch: '子批次',
    subbatch_num: '子批次号',
    storage_position: '存储位置',
    sub_lot: '亚批',
    product_code: '产品编码',
    product_name: '产品名称',
    product_spec: '产品规格',
    request_check: '请验',
    test_report: '检验报告',
    warehouse: '仓库',
    warehouse_name: '仓库名称',
    warehouse_code: '仓库编码',
    storage_region: '存储区域',
    storage_area_code: '存储区域编码',
    storage_pos_code: '存储位置编码',
    location_desc: '位置描述',
    apply_department: '请验部门',
    apply_item: '请验项目',
    sample_classify: '样品分类',
    applicant: '请验人',
    request_check_task: '请验步',
    request_check_order: '请验单',
    request_check_amount: '请验数量',
    request_check_product: '请验产品',
    request_check_confirm: '请验确认',
    request_check_finished: '已请验状态',
    request_check_completed: '请验成功',
    test_report_order: '检验报告单',
    test_report_task: '检验报告步'
    // raw_mat: '原料',
    // aux_mat: '辅料',
    // inner_mat: '内包装材料',
    // outer_mat: '外包装材料',
    // tobe_product: '待包装产品',
    // finished_product: '成品',
    // special_mat: '特殊物料',
    // special_product: '特殊产品',
    // intermediate_product: '中间品',
    // intermediate_products: '中间产品',
    // defect_product: '不良品',
    // consumable_mat: '耗材',
    // mat_loss_rate: '配料损失率',
    // conv_coef: '转换系数',
    // is_inventory_unit: '是否库存单位',
    // use_content: '使用含量',
    // distributable_quantity: '可分配量',
    // distribution_status: '分配状态',
    // wo_num: '工单号',
    // production_batch: '批次',
    // associated_batch: '关联批次',
    // order_type: '指令类型',
    // batch_production: '批生产',
    // batch_packing: '批包装',
    // metage: '称量',
    // metage_production: '称量生产',
    // process_program: '处理程序',
    // order_code: '指令单',
    // formula: '处方',
    // formula_desc: '处方描述',
    // formula_status: '处方状态',
    // valid_begin: '有效期开始',
    // valid_end: '有效期结束',
    // planned_quantity: '计划数量',
    // reference_quantity: '参考数量',
    // plan_batch: '计划批次',
    // plan_batch_quantity: '计划批次量',
    // plan_feed_quantity: '计划投料量',
    // error_upper: '误差上限',
    // error_lower: '误差下限',
    // plan_start_time: '计划开始时间',
    // plan_end_time: '计划结束时间',
    // main_formula: '主配方',
    // main_formula_desc: '主配方描述',
    // work_center: '工作中心',
    // wo_suspend: '工单暂停',
    // wo_terminate: '工单终止',
    // created: '创建',
    // published: '已发布',
    // prepared: '准备生产',
    // in_production: '生产中',
    // reported: '已报工',
    // aborted: '已废弃',
    // deviation_code: '偏差编码',
    // deviation_code_rule: '偏差编码规则',
    // deviation_level: '偏差等级',
    // deviation_level_setting: '偏差等级设置',
    // abnormal: '异常',
    // minor_deviation: '次要偏差',
    // major_deviation: '主要偏差',
    // significant_deviation: '重大偏差',
    // storage_timeout: '暂存超时',
    // main_formula_type: '主配方类型',
    // work_procedure: '工序',
    // install_process: '装置工序',
    // operation: '操作',
    // work_procedure_record: '工序记录',
    // auto_execution: '自动执行',
    // select_start: '选择开始',
    // select_end: '选择结束',
    // parallel_start: '并行开始',
    // parallel_finished: '并行结束',
    // judgment: '判断',
    // waiting: '等待',
    // work_report: '报工',
    // op_confirm: '操作确认',
    // work_proc_program: '工序程序',
    // op_program: '操作程序',
    // feeding: '投料',
    // mat_check: '物料核对',
    // return_mat: '退料',
    // process_output: '过程产出',
    // invent_creation: '库存创建',
    // container_binding: '容器绑定',
    // container_unbinding: '容器解绑',
    // device_communication: '设备通讯',
    // esign: '电子签名',
    // tag_jump: '标签跳转',
    // dry_off: '折干',
    // feeding_dry: '投料折干',
    // mat_usage: '物料使用',
    // mat_loss: '物料损耗',
    // mat_inquiry: '物料查询',
    // mat_balance: '物料结存',
    // equip_select: '设备选择',
    // equip_release: '设备释放',
    // attribute_query: '属性查询',
    // attribute_modify: '属性修改',
    // cell_passage: '细胞传代',
    // critical_data: '关键数据',
    // unit_type: '单位类型',
    // fixed_quantity: '定量',
    // fixed_unit: '定单位',
    // equivalent_weigh: '等价称量',
    // mat_source: '物料来源',
    // mat_ratio: '物料配比',
    // step: '步骤',
    // step_number: '步骤编号',
    // step_order: '步骤次序',
    // dose: '剂量',
    // is_fixed: '固定',
    // is_mixed: '混批',
    // error_type: '误差类型',
    // error_unit: '误差单位',
    // process_step: '产出步骤',
    // weigh_type: '称量类型',
    // odd: '零头',
    // compensation_mat: '补偿物料',
    // filling_mat: '填充物料',
    // packaging_mat: '包材',
    // output_type: '产出类型',
    // workshop_inventory: '车间库存'
  },
};
